version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.12.0
  - dependency-name: crontab
    versions:
    - 0.22.9
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: bleach
    versions:
    - 3.1.4
    - 3.3.0
  - dependency-name: python-box
    versions:
    - 5.2.0
  - dependency-name: jinja2
    versions:
    - 2.11.2
